include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.freezed.dart'
    - '**/*.g.dart'

linter:
  rules:
    always_declare_return_types: true
    always_use_package_imports: true
    avoid_dynamic_calls: true
    avoid_print: true
    directives_ordering: true
    missing_whitespace_between_adjacent_strings: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_single_quotes: true
    sort_constructors_first: true
